
---
sudo: false
language: c
compiler:
    - clang

os:
    - osx
      #    - linux

env:
    - ARCH=x86_64
    - ARCH=i686

notifications:
    email:
        on_success: always
        on_failure: always

script:
    - make
